### ISSUE TITLE
Exception thrown on logger init

### ISSUE THREAD

**Issue by ericavonb** [Clever/kayvee-js#9]
When I follow the example in the README.md, and do
```javascript
var kayvee = require('kayvee');
var log = kayvee.logger("logger-source");
```
it throws an exception.

Stack trace:

```
/home/vagrant/notes/node-scratch/node_modules/kayvee/lib-js/logger/logger.js:37
    this.logLvl = this._validateLogLvl(logLvl);
                       ^
TypeError: Object #<Object> has no method '_validateLogLvl'
    at Object.Logger (/home/vagrant/notes/node-scratch/node_modules/kayvee/lib-js/logger/logger.js:37:24)
    at Object.<anonymous> (/home/vagrant/notes/node-scratch/test.js:3:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

**Comment by mohit** [comment]
just ran into this error too. I don't know why this did not get any attention until now. Looking into this.

**Comment by mohit** [comment]
docs say 

```javascript
var kayvee = require('kayvee');
var log = new kayvee.logger("logger-source");
```
